# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Session configuration
    session:
        handler_id: null  # Use default session handler
        cookie_secure: auto  # Automatically set secure cookies for HTTPS
        cookie_samesite: lax  # Prevent CSRF attacks
        storage_factory_id: session.storage.factory.native  # Use native session storage

    # PHP errors logging
    php_errors:
        log: true

    # Validation configuration
    validation:
        enabled: true
        enable_annotations: false

    # Serializer configuration (if using API)
    serializer:
        enabled: true

    # Default locale
    default_locale: 'en'

    # Trusted proxies (if behind a load balancer or proxy)
    trusted_proxies: ~

    # Trusted hosts (for security)
    trusted_hosts: ~

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file