security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

            entry_point: form_login
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout             # Path to logout
                target: login # After logging out, redirect to login page
                invalidate_session: true
            remember_me:
                secret: '%kernel.secret%'    # Secret key for "Remember Me" functionality
                lifetime: 604800             # Remember me duration in seconds (1 week)
                path: /                      # Path to set the remember-me cookie for

    access_control:
    - { path: ^/index, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
    - { path: ^/reset_password, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/, roles: ROLE_USER }  # Restrict everything else to authenticated users
    


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10